/* Generated by Yosys 0.25+94 (git sha1 f7c1e4aad, gcc 7.5.0-3ubuntu1~18.04 -fPIC -Os) */

(* cells_not_processed =  1  *)
(* src = "./rtl/Example.v:4.1-23.10" *)
module Example(CLK, RST_N, UP_DN_N, Z);
  reg \$auto$verilog_backend.cc:2097:dump_module$6  = 0;
  (* src = "./rtl/Example.v:12.2-19.5" *)
  reg [11:0] _0_;
  (* src = "./rtl/Example.v:17.23-17.36" *)
  wire [11:0] _1_;
  (* src = "./rtl/Example.v:13.6-13.12" *)
  wire _2_;
  (* src = "./rtl/Example.v:17.39-17.52" *)
  wire [11:0] _3_;
  (* src = "./rtl/Example.v:17.13-17.52" *)
  wire [11:0] _4_;
  (* src = "./rtl/Example.v:5.8-5.11" *)
  input CLK;
  wire CLK;
  (* src = "./rtl/Example.v:6.8-6.13" *)
  input RST_N;
  wire RST_N;
  (* src = "./rtl/Example.v:7.8-7.15" *)
  input UP_DN_N;
  wire UP_DN_N;
  (* src = "./rtl/Example.v:8.16-8.17" *)
  output [11:0] Z;
  wire [11:0] Z;
  (* src = "./rtl/Example.v:10.13-10.18" *)
  reg [11:0] Z_reg;
  assign _1_ = Z_reg + (* src = "./rtl/Example.v:17.23-17.36" *) 12'h001;
  assign _2_ = ! (* src = "./rtl/Example.v:13.6-13.12" *) RST_N;
  assign _3_ = Z_reg - (* src = "./rtl/Example.v:17.39-17.52" *) 12'h001;
  assign _4_ = UP_DN_N ? (* src = "./rtl/Example.v:17.13-17.52" *) _1_ : _3_;
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$6 ) begin end
    _0_ = Z_reg;
    (* src = "./rtl/Example.v:13.3-18.6" *)
    casez (_2_)
      /* src = "./rtl/Example.v:13.6-13.12" */
      1'h1:
          _0_ = 12'h000;
      /* src = "./rtl/Example.v:16.3-16.7" */
      default:
          _0_ = _4_;
    endcase
  end
  always @(posedge CLK) begin
      Z_reg <= _0_;
  end
  always @(negedge RST_N) begin
      Z_reg <= _0_;
  end
  assign Z = Z_reg;
endmodule
